apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
spec:
  serviceName: "postgres-order"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config-demo-order
          ports:
            - containerPort: 5432
              name: postgredb
